version: '3'

services: 
  mysql-standalone: 
    image: 'mysql:5.7'
    environment: 
      - MYSQL_ROOT_PASSWORD=Shesha@98
      - MYSQL_PASSWORD=Shesha@98
      - MYSQL_DATABASE=sboot
    ports: 
      - "3306:3306"
  springboot-docker-container: 
    image: springboot-docker-container
    ports: 
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/sboot?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "Shesha@98"
    build: 
      context: "./"
      dockerfile: "Dockerfile"
    depends_on: 
      - mysql-standalone